-- Keymaps are automatically loaded on the VeryLazy event
-- Default keymaps that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/keymaps.lua
-- Add any additional keymaps here
--
vim.keymap.set("n", "<Leader>dd", function()
  require("dap").continue()
end, { desc = "Debug Continue" })
vim.keymap.set("n", "<Leader>do", function()
  require("dap").step_over()
end, { desc = "Step Over" })
vim.keymap.set("n", "<Leader>di", function()
  require("dap").step_into()
end, { desc = "Step Into" })
vim.keymap.set("n", "<Leader>du", function()
  require("dap").step_out()
end, { desc = "Step Out" })
vim.keymap.set("n", "<Leader>db", function()
  require("dap").toggle_breakpoint()
end, { desc = "Toggle Breakpoint" })
vim.keymap.set("n", "<Leader>dr", function()
  require("dap").repl.open()
end, { desc = "Repl Open" })
vim.keymap.set("n", "<Leader>dl", function()
  require("dap").run_last()
end, { desc = "Run Last" })
vim.keymap.set({ "n", "v" }, "<Leader>dh", function()
  require("dap.ui.widgets").hover()
end, { desc = "Hover" })
vim.keymap.set({ "n", "v" }, "<Leader>dr", function()
  require("dap.ui.widgets").preview()
end, { desc = "Preview" })
vim.keymap.set("n", "<Leader>df", function()
  local widgets = require("dap.ui.widgets")
  widgets.centered_float(widgets.frames)
end, { desc = "Frames" })
vim.keymap.set("n", "<Leader>ds", function()
  local widgets = require("dap.ui.widgets")
  widgets.centered_float(widgets.scopes)
end, { desc = "Scopes" })

vim.keymap.set("n", "<leader>zz", vim.cmd.NoNeckPain)
vim.keymap.set("i", "jj", "<Esc>", {})
vim.keymap.set("n", "<Leader>dt", function()
  require("dapui").toggle()
end, { desc = "Toggle UI" })

vim.keymap.set("n", "Q", "<nop>")

vim.keymap.set("n", "<leader>pv", vim.cmd.Ex, { desc = "Open File Explorer" })
vim.keymap.set("n", "<leader>co", function()
  vim.cmd.CopilotChatOpen()
end, { desc = "Opens the git hub copilot chat" })
